### ISSUE TITLE
kstar sometimes segfaults on the attached problem (and others of this size)

### ISSUE THREAD

**Issue by caelan** [ctpelok77/kstar#1]
[problem.pddl.txt](https://github.com/ctpelok77/kstar/files/4886742/problem.pddl.txt)
[domain.pddl.txt](https://github.com/ctpelok77/kstar/files/4886743/domain.pddl.txt)

I'm using the following command:

```./fast-downward.py --build release64 /Users/caelan/Programs/pddlstream/temp/domain.pddl /Users/caelan/Programs/pddlstream/temp/problem.pddl --search "kstar(blind(),q=10,k=10,cost_type=NORMAL,max_time=10)"```

**Comment by ctpelok77** [comment]
I am unable to replicate. 
Run multiple times, always finds all requested solutions in under half a second.

**Comment by ctpelok77** [comment]
Unable to replicate
