### ISSUE TITLE
Mismatch in # plans found

### ISSUE THREAD

**Issue by harshakokel** [ctpelok77/kstar#4]
Hello, 

We see a mismatch in the number of `found_plans/sas_plan` files (45) and the `Number of plans found:` (15) in the output log. To replicate the issue, use `--search 'kstar(blind,k=100)'` with the attached [domain.txt](https://github.com/ctpelok77/kstar/files/7117602/domain.txt) and [problem.txt](https://github.com/ctpelok77/kstar/files/7117604/problem.txt). 

Similar behavior is observed with `lmcut` heuristic as well.

Regards,
Harsha

**Comment by ctpelok77** [comment]
It seems like the same plans are dumped three times.

**Comment by ctpelok77** [comment]
I have added a fix in issue4 branch, will set up an experiment

**Comment by ctpelok77** [comment]
Merged.
